### ISSUE TITLE
Borderless, please!

### ISSUE THREAD

**Issue by MDNSSKNGHT** [nik1178/NJDark#1]
The theme is so good actually, but would be even better without those borders!
(Mind adding it as a variant?)

**Comment by nik1178** [comment]
Noted. It will hopefully be done by the end of the weekend or sooner.

**Comment by MDNSSKNGHT** [comment]
Thank you!

**Comment by nik1178** [comment]
Updated. Is this what you had in mind, or do you want me to change anything else?

**Comment by MDNSSKNGHT** [comment]
> Updated. Is this what you had in mind, or do you want me to change anything else?

Yeah, many thanks, going to add it as another issue!
